{

  // This example shows how to generate random numbers, fill and plot histograms, and perform a fit using ROOT

  double b_mgg , s_mgg ;

  TH1F* h_s = new TH1F("h_s","h_s",120,100,160);
  TH1F* h_b = new TH1F("h_b","h_b",120,100,160);
  for( int i = 0 ; i < 100000 ; i ++ )
    {
      s_mgg = gRandom->Gaus( 125, 2);
      b_mgg = gRandom->Exp(500);

      double signal_weight = 0.01;

      h_s -> Fill( s_mgg , signal_weight) ;
      h_b -> Fill( b_mgg ) ; 

      //      cout << " randomized s_mgg and b_mgg " << s_mgg << " " << b_mgg << endl;
    }

  TCanvas *c = new TCanvas();

  h_s->Draw();
  h_b->Draw("same");

  c->SaveAs("plot_mass_signal_over_background.png");




  TCanvas *c_1 = new TCanvas();

  h_s->SetLineWidth(2);
  h_s->SetLineColor(2);
  h_s->SetLineStyle(1);
  h_s->SetFillColor(2);

  h_b->SetLineWidth(2);
  h_b->SetLineColor(1);
  h_b->SetLineStyle(1);
  h_b->SetFillColor(5);

  double max_s = h_s->GetMaximum() * 3;

  h_s->GetXaxis()->SetTitle("M_{#gamma#gamma} [GeV]");
  h_s->GetYaxis()->SetTitle("Entries");

  h_s->GetYaxis()->SetRangeUser(0,1.5*max_s);

  h_s->Draw();
  h_b->Draw("same");

  c_1->SaveAs("plot_mass_signal_over_background_1.png");





  TCanvas *c_2 = new TCanvas();

  h_s->SetLineWidth(2);
  h_s->SetLineColor(2);
  h_s->SetLineStyle(1);
  h_s->SetFillColor(2);

  h_b->SetLineWidth(2);
  h_b->SetLineColor(1);
  h_b->SetLineStyle(1);
  h_b->SetFillColor(5);


  THStack *sk = new THStack("sk","sk");

  sk->Add(h_b);
  sk->Add(h_s);
  double max_b = h_b->GetMaximum();
  sk->Draw();
  // Note the sequence of Draw() and GetXaxis() for a THStack object
  sk->GetXaxis()->SetTitle("M_{#gamma#gamma} [GeV]");
  sk->GetYaxis()->SetTitle("Entries");


  c_2->SaveAs("plot_mass_signal_over_background_2.png");




  TCanvas *c_3 = new TCanvas();

  h_s->SetLineWidth(2);
  h_s->SetLineColor(2);
  h_s->SetLineStyle(1);
  h_s->SetFillColor(2);

  h_b->SetLineWidth(2);
  h_b->SetLineColor(1);
  h_b->SetLineStyle(1);
  h_b->SetFillColor(5);


  THStack *sk_3 = new THStack();
  sk_3->Add(h_b);
  sk_3->Add(h_s);
  sk_3->Draw();
  sk_3->GetXaxis()->SetTitle("M_{#gamma#gamma} [GeV]");
  sk_3->GetYaxis()->SetTitle("Entries");

  TLegend leg_3(0.65,0.8,0.85,0.9);
  leg_3.AddEntry(h_s,"H #rightarrow #gamma#gamma","FL");
  leg_3.AddEntry(h_b,"Background","F");
  leg_3.SetLineColor(0);
  leg_3.SetTextSize(0.05);
  leg_3.SetShadowColor(0);
  leg_3.SetFillStyle(0);
  leg_3.Draw();

  TLatex cap_3;
  cap_3.SetNDC();
  cap_3.SetTextColor(1);
  cap_3.DrawLatex(0.2,0.25,"#int Ldt = 20.3 fb^{-1} #sqrt{s} = 8 TeV");
  cap_3.DrawLatex(0.2,0.35,"ATLAS Internal");

  c_3->SaveAs("plot_mass_signal_over_background_3.png");

  // You should check out the two files generated by the lines below.

  c_3->SaveAs("plot_mass_signal_over_background_3.C");

  c_3->SaveAs("plot_mass_signal_over_background_3.eps");




}
